
## Customer Segmentation Analysis

Step 1 : Import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Step 2 : Load cleaned dataset

In [3]:
df = pd.read_csv("C:\\Users\\cheta\\Desktop\\Customer_Analytics_&_Insights\\data\\cleaned_data.csv")

df.head()

,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age,Total_Spending,Children
0,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,88,...,0,0,0,0,3,11,1,69,1617,0
1,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,1,...,0,0,0,0,3,11,0,72,27,2
2,1965,Graduation,Married,71613.0,0,0,2013-08-21,26,426,49,...,0,0,0,0,3,11,0,61,776,0
3,1984,Graduation,Married,26646.0,1,0,2014-02-10,26,11,4,...,0,0,0,0,3,11,0,42,53,1
4,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,43,...,0,0,0,0,3,11,0,45,422,1

Step 3 : Dataset Overview

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year_Birth           2240 non-null   int64
 1   Education            2240 non-null   object
 2   Marital_Status       2240 non-null   object
 3   Income               2240 non-null   float64
 4   Kidhome              2240 non-null   int64
 5   Teenhome             2240 non-null   int64
 6   Dt_Customer          2240 non-null   object
 7   Recency              2240 non-null   int64
 8   MntWines             2240 non-null   int64
 9   MntFruits            2240 non-null   int64
 10  MntMeatProducts      2240 non-null   int64
 11  MntFishProducts      2240 non-null   int64
 12  MntSweetProducts     2240 non-null   int64
 13  MntGoldProds         2240 non-null   int64
 14  NumDealsPurchases    2240 non-null   int64
 15  NumWebPurchases      2240 non-null   int64
 16  NumCatalogPurchases  2240 non-null   int64
 17  NumStorePurchases    2240 non-null   int64
 18  NumWebVisitsMonth    2240 non-null   int64
 19  AcceptedCmp3         2240 non-null   int64
 20  AcceptedCmp4         2240 non-null   int64
 21  AcceptedCmp5         2240 non-null   int64
 22  AcceptedCmp1         2240 non-null   int64
 23  AcceptedCmp2         2240 non-null   int64
 24  Complain             2240 non-null   int64
 25  Z_CostContact        2240 non-null   int64
 26  Z_Revenue            2240 non-null   int64
 27  Response             2240 non-null   int64
 28  Age                  2240 non-null   int64
 29  Total_Spending       2240 non-null   int64
 30  Children             2240 non-null   int64
dtypes: float64(1), int64(27), object(3)
memory usage: 542.6+ KB

,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age,Total_Spending,Children
count,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000,2240.000000,2240.000000,2240.000000
mean,1968.805804,52237.975446,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,27.062946,...,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107,57.194196,605.798214,0.950446
std,11.984069,25037.955891,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,41.280498,...,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274,11.984069,602.249288,0.751803
min,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,30.000000,5.000000,0.000000
25%,1959.000000,35538.750000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,49.000000,68.750000,0.000000
50%,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,8.000000,...,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,56.000000,396.000000,1.000000
75%,1977.000000,68289.750000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,33.000000,...,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,67.000000,1045.500000,1.000000
max,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,263.000000,...,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000,133.000000,2525.000000,3.000000

Step 4 : KPI Calculations

In [7]:
# KPI 1: Average Customer Spending

total_spending = df['Total_Spending'].sum()

total_customers = len(df)

avg_customer_spending = total_spending / total_customers

print("Average Customer Spending:", avg_customer_spending)

# KPI 2: Campaign Response Rate

responded_customers = df['Response'].sum()

response_rate = (responded_customers / total_customers) * 100

print("Campaign Response Rate:", response_rate, "%")

# KPI 3: Average Income

avg_income = df['Income'].mean()

print("Average Income:", avg_income)

# KPI 4: Web Purchase Rate

total_web = df['NumWebPurchases'].sum()

total_store = df['NumStorePurchases'].sum()

total_catalog = df['NumCatalogPurchases'].sum()

total_purchases = total_web + total_store + total_catalog

web_purchase_rate = (total_web / total_purchases) * 100

print("Web Purchase Rate:", web_purchase_rate, "%")

# KPI 5: Complaint Rate

total_complaints = df['Complain'].sum()

complaint_rate = (total_complaints / total_customers) * 100

print("Complaint Rate:", complaint_rate, "%")

Average Customer Spending: 605.7982142857143
Campaign Response Rate: 14.910714285714285 %
Average Income: 52237.97544642857
Web Purchase Rate: 32.58198910372823 %
Complaint Rate: 0.9375 %

Step 5 : Customer Segementation

In [8]:
df['Customer_Segment'] = pd.qcut(
    df['Total_Spending'],
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value']
)

df[['Customer_Segment', 'Total_Spending']].head()

  Customer_Segment  Total_Spending
0       High Value            1617
1        Low Value              27
2     Medium Value             776
3        Low Value              53
4     Medium Value             422

Step 6 : Segment Calculations

In [13]:
segment_analysis = df.groupby('Customer_Segment')[
    ['Income', 'Total_Spending']
].mean()

segment_analysis

C:\Users\cheta\AppData\Local\Temp\ipykernel_28540\1937493779.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  segment_analysis = df.groupby('Customer_Segment')[

                        Income  Total_Spending
Customer_Segment
Low Value         33003.935160       51.219251
Medium Value      50839.973154      412.975839
High Value        72892.023427     1353.425703

Step 7 : Insights

 **KPI 1: Average Customer Spending**

Formula:

Average Customer Spending = Total Spending / Total Customers

This KPI measures the average revenue contribution per customer.

**KPI 2: Campaign Response Rate**

Formula:

Campaign Response Rate =
(Number of Customers Responded / Total Customers) × 100

This KPI measures the effectiveness of marketing campaigns.

**KPI 3: Average Income**

Formula:

Average Income =
Total Income / Total Customers

This KPI shows customer purchasing capability.

 **KPI 4: Web Purchase Rate**

Formula:

Web Purchase Rate =
(Total Web Purchases / Total Purchases) × 100

This KPI measures customer engagement through online channels.

**KPI 5: Complaint Rate**

Formula:

Complaint Rate =
(Number of Complaints / Total Customers) × 100

This KPI helps evaluate customer satisfaction.

**Final Insights**

- High Value customers have significantly higher income levels
- Customers with higher income spend more overall
- Wine and meat products contribute heavily to total spending
- Web purchases are highly popular among customers
- Campaign response rate is relatively low
- Customer segmentation helps identify valuable customer groups